name = "ask-my-doc"
main = "src/index.ts"
compatibility_date = "2024-07-25"

# R2 Binding
[[r2_buckets]]
binding = "R2"
bucket_name = "ask-my-doc"

# R2 Binding for static assets like openapi.json
[[r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "ask-my-doc-static"

# D1 Binding
[[d1_databases]]
binding = "DB"
database_name = "ask-my-doc"
database_id = "8260783c-903f-4c51-95dd-865f9ad2bbab"
migrations_dir = "migrations"

# Vectorize Binding
[[vectorize]]
binding = "VECTORIZE"
index_name = "ask-my-doc"

# AI Binding
[ai]
binding = "AI"
