name = "ask-my-doc"
main = "src/index.ts"
compatibility_date = "2024-07-25"

# R2 Binding
[[r2_buckets]]
binding = "R2"
bucket_name = "ask-my-doc"

# This binding tells Wrangler to serve the contents of the `./public` directory
# from a special R2 bucket. It's a modern and automated alternative to manually
# creating and binding a bucket for static files.
[site]
bucket = "./public"
# This binding is the new standard. It automatically creates an ASSETS binding.
# The previous STATIC_ASSETS binding is no longer needed.
# binding = "ASSETS" # This is automatically created by the `[site]` binding.

# D1 Binding
[[d1_databases]]
binding = "DB"
database_name = "ask-my-doc"
database_id = "8260783c-903f-4c51-95dd-865f9ad2bbab"
migrations_dir = "migrations"

# Vectorize Binding
[[vectorize]]
binding = "VECTORIZE"
index_name = "ask-my-doc"

# AI Binding
[ai]
binding = "AI"
